### PR TITLE
egdl-1429: update plugin versions + fix checkstyle bug

### PR DESCRIPTION
**Pull request by shermosa**
- **updated the plugin versions**
- **fixed a bug** that appears when you update the version of the checkstyle plugin; you have to change the location of _LineLength_ so that its parent is not _TreeWalker._

### CODE REVIEW

**Review by massdosage — APPROVED** [review]
Looks good!

**Review by patduin — CHANGES_REQUESTED** [review]
looks good but update the CHANGELOG.md please :)

**Comment by massdosage** [comment]
> looks good but update the CHANGELOG.md please :)

It is changed?

**Review by patduin — APPROVED** [review]
my bad already there.

**Pull request merged**
